### PR TITLE
Fix issue with location urls

### LINKED ISSUE #1: Package generates improper urls in sitemap.xml
**Describe the bug**

**To Reproduce**
Follow all the normal steps to set this up with rollup or vite which is built on rollup.

**Expected behaviour**
The generated sitemap.xml has all the urls in the right format.

**Actual behaviour**
The generated sitemap has urls that throw an error. The double slash is replaced by a single slash. ie., https://domain.com becomes https:/domain.com (note the single forward slash instead of two).

**Screenshots**
This image is a screenshot from the readme file. 
Please note the missing slash after the protocol, i.e., `https:/` instead of `https://`.
image

**Environment (please complete the following information):**
Not environment dependent.

Anyway:
 - OS: Ubuntu 22.04
 - Node  18.x.x, 20.x.x
 - Package 0.1.0

### PR DESCRIPTION
**Pull request by Aniganesh**
## Bug fix

- [X] Fixes #1 
This PR fixes the issue I mentioned above

### CODE REVIEW

**Comment by aminnairi** [comment]
Thank you for your contributions!

I was thinking of adding unit tests in order to prevent regressions.

Would you mind adding some in order to tests those different cases?

- Base url: `https://site.com`, location: `home`
- Base url: `https://site.com`, location: `/home`
- Base url: `https://site.com`, location: `home/`
- Base url: `https://site.com`, location: `/home/`
- Base url: `https://site.com`/, location: `/home/`
- Base url: `https://site.com//`, location: `//home/`

**Comment by Aniganesh** [comment]
Sure. Will do.

**Comment by Aniganesh** [comment]
Do you have any recommendations or preferences for testing libraries? Also some pointers would be useful.

**Comment by aminnairi** [comment]
> Do you have any recommendations or preferences for testing libraries? Also some pointers would be useful.

I'm confortable with Vitest since it go pair with the Rollup/Vite ecosystem. I would appreciate tests under that library but any other one would do the job just fine I guess.

I was thinking about extracting the core logic of this plugin and testing it, since testing Rollup plugins can be a tedious tasks since we have to mock the whole API contains about a large amout of methods that we would probably not need anytime soon for this library.

That way, we can test that the core functionalities work as expected and would be able to import it inside the exported plugin.

If you have any suggestions feel free to share them!

**Pull request merged**
